### ISSUE TITLE
Plz create tag ver.

### ISSUE THREAD

**Issue by Toxenskiy** [rayferric/dungeon-seed#1]
Please/

**Comment by Toxenskiy** [comment]
software not work

**Comment by rayferric** [comment]
Hello! The "software" is not a standalone program, but bits of code I've written to crack Minecraft 1.12.2 world seeds. If you want to use it yourself, you will have to install a Java IDE and edit the project there by inputting own values. Three example dungeons are provided from which you can generate the seed and jump into Minecraft to see them in-person.

As for the IDE, I highly recommend **[JetBrains IntelliJ IDEA](https://download.jetbrains.com/idea/ideaIC-2021.3.exe)**.
Importing this project is as simple as opening the downloaded folder from the **File** menu.

Download project files **[here](https://github.com/rayferric/dungeon-seed/archive/refs/heads/main.zip)**.

Feel free to submit in this issue any upcoming questions regarding the process and I will be happy to assist you. Have a great day!

**Comment by Toxenskiy** [comment]
Yesterday I already figured out everything works, but it does not work on servers with a paper-core, as I understand it.

**Comment by Toxenskiy** [comment]
![image](https://user-images.githubusercontent.com/55586522/147435084-b2ac7c4a-5751-4738-ba3d-a939312e7f79.png)

**Comment by Toxenskiy** [comment]
Is it possible to determine the seed by End World?

**Comment by rayferric** [comment]
It will work if dungeon generation remains unchanged on the server, i.e. dungeons generate the same way as in Vanilla game. I have actually tested it once with a PaperMC server and it has worked just fine. This method is vulnerable to even the slightest trace of water and lava lakes, so, to be safe, you must use Freecam or XRay to determine that all neighboring chunks are clear of lakes as well.
Dungeons only generate in the overworld, but seed reversal is still possible through obsidian pillars in the End plus a few structures.
For that, check out those useful projects made by members of The Minecraft@Home community:

This might be the most promising tool with a web GUI:
https://github.com/hube12/MinecraftSeedCrackingC/

Other 1.16+ in-game crackers:
https://github.com/KaptainWutax/SeedCracker/
https://github.com/19MisterX98/SeedcrackerX/

Those are only a few of the existing tools and there surely is a multitude of others, so go search for yourself.
(If dungeons really don't work. I would give dungeon-seed a try with another triple, perhaps in a Vanilla world for testing.)
